# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bizgo < Formula
  desc ""
  homepage "https://github.com/Bijay2052/biz-go"
  version "1.0.1"

  on_macos do
    url "https://github.com/Bijay2052/biz-go/releases/download/v1.0.1/biz-go_1.0.1_darwin_all.tar.gz"
    sha256 "4da6abb083bd36926a2e755a59373e9d6ab8bf65d747ddfc73822360fc487bd8"

    def install
      bin.install "biz-go"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Bijay2052/biz-go/releases/download/v1.0.1/biz-go_1.0.1_linux_arm64.tar.gz"
      sha256 "a44839cafb3c8d7f4ca9758e37821378875924fa463e8ec85d615ab062ba83a1"

      def install
        bin.install "bizgo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Bijay2052/biz-go/releases/download/v1.0.1/biz-go_1.0.1_linux_amd64.tar.gz"
      sha256 "e7de57e7f281afc86f70319efaf0d76777a7fc6dfb21ad9825884750ad2921bb"

      def install
        bin.install "bizgo"
      end
    end
  end
end
