# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bizgo < Formula
  desc ""
  homepage "https://github.com/Bijay2052/biz-go"
  version "0.0.4"

  on_macos do
    url "https://github.com/Bijay2052/biz-go/releases/download/v0.0.4/biz-go_0.0.4_darwin_all.tar.gz"
    sha256 "ec2a35ca6d150684dfba1f6a6ed77423583daa289e48fa83e1d26c9724a43bd0"

    def install
      bin.install "biz-go"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Bijay2052/biz-go/releases/download/v0.0.4/biz-go_0.0.4_linux_arm64.tar.gz"
      sha256 "4080879a4d950e8a422ab36f5b1f54ffc1861e2ac25247eb2c0ce8ee8554721a"

      def install
        bin.install "mediumautopost"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Bijay2052/biz-go/releases/download/v0.0.4/biz-go_0.0.4_linux_amd64.tar.gz"
      sha256 "690c2140e1b648d884cfd37164a8e49e541ddb28c7cf7a591cb5c5f38ad48608"

      def install
        bin.install "mediumautopost"
      end
    end
  end
end
